from selenium.webdriver.common.by import By

class Service():
    COOKIE_BUTTON = (By.CSS_SELECTOR, "div.privacy-wrapper.ng-scope > button:nth-child(4)")
    COOKIE_TEXT = (By.CSS_SELECTOR, "div.privacy-wrapper.ng-scope > h3:nth-child(1)")
    PROFITABLY_BUTTON = (By.CSS_SELECTOR, "li.shipper-feature:nth-child(2) div.shipper-feature__text:nth-child(2) p.shipper-feature__title > a:nth-child(1)")
    SAFELY_BUTTON = (By.CSS_SELECTOR, "li.shipper-feature:nth-child(3) div.shipper-feature__text:nth-child(2) p.shipper-feature__title > a:nth-child(1)")
    RELIABLY_BUTTON = (By.CSS_SELECTOR, "li.shipper-feature:nth-child(1) div.shipper-feature__text:nth-child(2) p.shipper-feature__title > a:nth-child(1)")
    TRCOIN_BUTTON = (By.CSS_SELECTOR, "div.shipper.ng-scope section:nth-child(4) div.enter-tr-coin div.learn a:nth-child(1) > div.learn-info")
    BUSINES_BUTON = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[7]/div[1]/div[3]/div[1]/button[1]")
    NAVI_BUTTON = (By.CSS_SELECTOR, "div.wrapper div.business-block.naviads div.button-wrapper.desk-btn:nth-child(3) > a.naviads:nth-child(2)")
    TMS = (By.CSS_SELECTOR, "#bussines-control .block-control .wrapper-control .tms-control button.blue-control-btn")
    TR_MARKET = (By.CSS_SELECTOR, "div.title-trmarket div.button-wrapper.desk-btn:nth-child(4) > button.trmarket-btn")
    TR_MARKET_AD_ADD = (By.CSS_SELECTOR, ".slick-slider .slick-list, .slick-slider .slick-track")
    TR_MARKET_WATCH_AD = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[5]/div[2]/div[4]/div[2]/div[1]/div[2]/span[1]")
    TOKEN = (By.CSS_SELECTOR,"input[type='text' i]")
    TOKEN_SUBMIT = (By.CSS_SELECTOR,"input[type='submit' i]")

    ########ORDER####

    MAKE_AN_ORDER_LEGULAR_BUTTON = (By.CSS_SELECTOR, "p.custom-checkbox.blue.freight-form__field-label.ng-scope label:nth-child(2) > span.outbox")
    MAKE_AN_ORDER_LEGULAR_AGREE_BUTTON = (By.CSS_SELECTOR, "div.button-wrapper > button.green")
    MAKE_AN_ORDER_FROM = (By.CSS_SELECTOR, "#cityAddressInput0")
    MAKE_AN_ORDER_WHERE = (By.CSS_SELECTOR, "#cityAddressInput1")
    MAKE_AN_ORDER_CARGO = (By.CSS_SELECTOR, "#cargoName")
    MAKE_AN_ORDER_WEIGHT = (By.CSS_SELECTOR, "#cargoWeight")
    MAKE_AN_ORDER_VOLUME = (By.CSS_SELECTOR, "#cargoVolume")
    MAKE_AN_ORDER_TYPE_OF_CAR = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[3]/div[2]")
    MAKE_AN_ORDER_TYPE_OF_DOWNLOAD = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[3]/div[3]")
    MAKE_AN_ORDER_PRICE = (By.CSS_SELECTOR, ".freight-form__field .freight-form__field--new-fracht .fracht-wrapper .fracht-wrapper__fratch")
    MAKE_AN_ORDER_TYPE_OF_DOWNLOAD_AGREE = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[3]/div[3]/checklist-dropdown[1]/div[1]/div[2]/div[1]/div[1]/p[1]/label[1]/span[1]")
    MAKE_AN_ORDER_TYPE_OF_CAR_AGREE = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[3]/div[2]/checklist-dropdown[1]/div[1]/div[2]/div[1]/div[1]/p[1]/label[1]/span[1]")
    MAKE_AN_ORDER_CUSTOMER_NAME = (By.CSS_SELECTOR, "div.freight-form__field.ng-scope:nth-child(1) > input.freight-form__field-control.default.ym-record-keys.ng-pristine.ng-untouched.ng-valid.ng-empty.invalid-model")
    MAKE_AN_ORDER_CUSTOMER_PHONE = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[2]/div[2]/div[1]/div[5]/div[2]/div[2]/div[2]/input[1]")
    MAKE_AN_ORDER_BUTTON_PUT = (By.CSS_SELECTOR, "div.wrapper-form-order button.green.default.saveStep.landing-green:nth-child(6) > span:nth-child(1)")
    MAKE_AN_ORDER_ALERT_BUTTON = (By.CSS_SELECTOR, "div.customModal.info.ng-scope.orderSuccessGuestModal > button.close")
    MAKE_AN_ORDER_DELETE_BUTTON = (By.XPATH, "//a[contains(text(),'Скасувати замовлення')]")
    MAKE_AN_ORDER_DELETE_AGREE_BUTTON = (By.CSS_SELECTOR, "div.customModal.prompt.ng-scope div.modal-footer > button.blue.ng-binding:nth-child(2)")
    MAKE_AN_ORDER_DELETE_AGREE_BUTTON_SECOND = (By.CSS_SELECTOR, "div.modal-content div.customModal.info.ng-scope > button.close")
    MAKE_AN_ORDER_BACK_BUTTON = (By.CSS_SELECTOR, "div.order-realtime-wrapper.ng-scope.order-token div.header div.left div:nth-child(1) > a.vars.ng-scope")
    MAKE_AN_ORDER_EMPTY_COLUMN = (By.CSS_SELECTOR, "div.modal-wrapper.normal.ng-scope div.white > h3.center.ng-binding:nth-child(3)")
    MAKE_AN_ORDER_ALERT_TRY = (By.CSS_SELECTOR, "div.modal-wrapper.normal.ng-scope div.white > p.center:nth-child(3)")
    AUTOCOMPLITE_ORDER_FROM_TOWN = (By.CSS_SELECTOR, "#main-page-make-order > div > div.part2 > div.wrapper-way > ul > li.li--block.ng-scope.loading > div.input-wrapper.first-input.ng-scope > div.new-autocomplete.new-autocomplete--visible > div.items > ul > li:nth-child(2) > span")
    AUTOCOMPLITE_ORDER_FROM_ADRESS = (By.CSS_SELECTOR, "#main-page-make-order > div > div.part2 > div.wrapper-way > ul > li.li--block.ng-scope.loading > div.input-wrapper.first-input.ng-scope > div.new-autocomplete.new-autocomplete--visible > div.items > ul > li:nth-child(4) > span")
    AUTOCOMPLITE_ORDER_WHERE_TOWN = (By.CSS_SELECTOR, "#main-page-make-order > div > div.part2 > div.wrapper-way > ul > li.li--block.ng-scope.unloading > div.input-wrapper.first-input.ng-scope > div.new-autocomplete.new-autocomplete--visible > div.items > ul > li:nth-child(1)")
    AUTOCOMPLITE_ORDER_WHERE_ADRESS = (By.CSS_SELECTOR, "#main-page-make-order > div > div.part2 > div.wrapper-way > ul > li.li--block.ng-scope.unloading > div.input-wrapper.first-input.ng-scope > div.new-autocomplete.new-autocomplete--visible > div.items > ul > li:nth-child(3) > span")

   
######## TARIF CALCULATOR###########

    TARIFF_CALCULATOR_FROM = (By.CSS_SELECTOR, "div.rate-calc-block div.calculate-item.ng-scope:nth-child(3) div.calculate-item__item.first:nth-child(1) div.route-calculation__flag-wrapper.first-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    TARIFF_CALCULATOR_WHERE = (By.CSS_SELECTOR, "div.rate-calc-block div.calculate-item.ng-scope:nth-child(3) div.calculate-item__item.second:nth-child(2) div.route-calculation__flag-wrapper.second-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    TARIFF_CALCULATOR_TONNAGE = (By.CSS_SELECTOR, "div.shipper.ng-scope section.default.ng-scope:nth-child(2) div.route-block-wrapper.wrapper--fixed.ng-scope div.rate-calc-block div.calculate-item.ng-scope:nth-child(3) div.calculate-item__item.third:nth-child(3) div.tonnage > input.form-control.ym-record-keys.direction.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    TARIFF_CALCULATOR_BUTTON = (By.CSS_SELECTOR, "#route-calc-section .route-block-wrapper .rate-calc-block .calculate-item .calculate-button")
    TARIFF_CALCULATOR_FROM_AUTOCOMPLITE = (By.CSS_SELECTOR, "#route-calc-section > div > div.rate-calc-block > div > div.calculate-item__item.first > div > div.new-autocomplete.new-autocomplete--visible > div > ul > li:nth-child(2) > span")
    TARIFF_CALCULATOR_WHERE_AUTOCOMPLITE = (By.CSS_SELECTOR, "#route-calc-section > div > div.rate-calc-block > div > div.calculate-item__item.second > div > div.new-autocomplete.new-autocomplete--visible > div > ul > li:nth-child(1) > span")
    
######ROUTE CALCULATOR########

    ROUTE_CALCULATION_FROM = (By.CSS_SELECTOR, "#route-calc-section > div > div.wrapper-fuel-calc-block > div.fuel-calc-block > div > div.fuel-calc-block-left > div > div.calculate-item__item.first > div > input")
    ROUTE_CALCULATION_FROM_AUTOCOMPLITE = (By.CSS_SELECTOR, "#route-calc-section > div > div.wrapper-fuel-calc-block > div.fuel-calc-block > div > div.fuel-calc-block-left > div > div.calculate-item__item.first > div > div.new-autocomplete.new-autocomplete--visible > div > ul > li:nth-child(2) > span")
    ROUTE_CALCULATION_WHERE = (By.CSS_SELECTOR, "#route-calc-section > div > div.wrapper-fuel-calc-block > div.fuel-calc-block > div > div.fuel-calc-block-left > div > div.calculate-item__item.second > div > input")
    ROUTE_CALCULATION_WHERE_AUTOCOMPLITE = (By.CSS_SELECTOR, "#route-calc-section > div > div.wrapper-fuel-calc-block > div.fuel-calc-block > div > div.fuel-calc-block-left > div > div.calculate-item__item.second > div > div.new-autocomplete.new-autocomplete--visible > div > ul > li:nth-child(1) > span")
    ROUTE_CALCULATION_FUEL = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[3]/div[1]/input[1]")
    ROUTE_CALCULATION_BUTTON_MAIN = (By.CSS_SELECTOR, "#route-calc-section .route-block-wrapper .wrapper-fuel-calc-block .fuel-calc-block .calculate-item .calculate-button")
    ROUTE_CALCULATION_BUTTON_EGREE = (By.CSS_SELECTOR, "div.distance__way-left div.distance-calculator div.distance-calculator__points:nth-child(1) > button.calculate-button:nth-child(4)")
    ROUTE_CALCULATION_ALERT_TEXT = (By.CSS_SELECTOR, "div.modal-content div.modal-wrapper.normal.ng-scope div.white > p.center.description")
    ROUTE_CALCULATION_ALERT_OK = (By.CSS_SELECTOR, "div.modal-wrapper.normal.ng-scope div.white div.modal-footer > button.btn.btn-default.next")
    ROUTE_CALCULATION_FUEL_SECOND = (By.CSS_SELECTOR, "#distance > div > div.distance__way-container > div > div.distance-calculator > div:nth-child(2) > div > div.distance-calculator__param.distance-calculator__param--double > div:nth-child(1) > div.distance-calculator__param-body > input")
    ROUTE_CALCULATION_PRICE_LITR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/input[1]")
    ROUTE_CALCULATION_BUTTON_BACK = (By.CSS_SELECTOR, "div.map-links span.link:nth-child(1) > a:nth-child(1)")
    ROUTE_CALCULATION_ORDER = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/p[1]")
    ROUTE_CALCULATION_SIDAN = (By.CSS_SELECTOR, "div.distance-calculator div.distance-calculator__params.distance-calculator__params--right div.distance-calculator__param:nth-child(2) div.distance-calculator__param-body div.distance-calculator__radio-group div.custom-radio.custom-radio--circle:nth-child(1) label:nth-child(2) > div.radio-button")
    ROUTE_CALCULATION_DISEL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/p[2]/label[1]")
    ROUTE_CALCULATION_GAS = (By.CSS_SELECTOR, "div.wrapper-fuel-calc-block div.fuel-calc-block div.fuel-calc-content:nth-child(2) div.fuel-calc-block-right.calculate-item div.side-block-radios.radios2.ng-scope:nth-child(1) p.custom-radiobutton:nth-child(3) > label:nth-child(2)")
    COUNTRY_FIRST_DROPDOWN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]")
    NAME_COUNTRY_FIRST = (By.CSS_SELECTOR, "#focusOnClickWhereFrom")
    COUNTRY_INPUT_FIRST = (By.CSS_SELECTOR, "div.route-calculation__flag-wrapper.first-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-valid.ng-isolate-scope.ng-empty.ng-touchedw")
    COUNTRY_SECOND_DROPDOWN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]")
    NAME_COUNTRY_SECOND = (By.CSS_SELECTOR, "#focusOnClickWhere")
    COUNTRY_INPUT_SECOND = (By.CSS_SELECTOR, "div.calculate-item.ng-scope:nth-child(3) div.calculate-item__item.second:nth-child(2) div.route-calculation__flag-wrapper.second-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    COUNTRY_THIRD_DROPDOWN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]")
    NAME_COUNTRY_THIRD = (By.CSS_SELECTOR, "#focusOnClickWhereFrom")
    COUNTRY_INPUT_THIRD = (By.CSS_SELECTOR, "div.route-calculation__flag-wrapper.first-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    COUNTRY_FOURTH_DROPDOWN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]")
    NAME_COUNTRY_FOURTH = (By.CSS_SELECTOR, "#focusOnClickWhere")
    COUNTRY_INPUT_FOURTH = (By.CSS_SELECTOR, "div.shipper.ng-scope section.default.ng-scope:nth-child(2) div.route-block-wrapper.wrapper--fixed.ng-scope div.wrapper-fuel-calc-block div.fuel-calc-block div.fuel-calc-content:nth-child(2) div.fuel-calc-block-left div.calculate-item.ng-scope div.calculate-item__item.second:nth-child(2) div.route-calculation__flag-wrapper.second-flag-wrapper > input.form-control.autocity.landing-input.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    FLAG_FIRST = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/div[2]/div[1]/div[1]/li[171]/div[1]")
    FLAG_SECOND = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/div[2]/div[1]/div[1]/li[171]")
    FLAG_THIRD = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/div[2]/div[1]/div[1]/li[171]")
    FLAG_FOUTH = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/div[2]/div[1]/div[1]/li[171]")
    CARGO_TONNAGE = (By.CSS_SELECTOR,"div.tonnage > input.form-control.ym-record-keys.direction.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-empty")
    CALCULATE_BUTTON = (By.CSS_SELECTOR,"button[class='calculate-button order']")
    BUTTON_DISTANCE = (By.CSS_SELECTOR, "button[class='calculate-button button-distance']")
    GOOGLE_BUTTON_ONE = (By.CSS_SELECTOR, "ul.mobile-app__app-list li.mobile-app__app-item:nth-child(1) a.mobile-app__app-link.mobile-app__app-link--google-play > img:nth-child(1)")
    APP_BUTTON_ONE = (By.CSS_SELECTOR, "ul.mobile-app__app-list li.mobile-app__app-item:nth-child(2) a.mobile-app__app-link.mobile-app__app-link--app-store > img:nth-child(1)")
  


class Footer():
    CARRIER_BUTTON = (By.CSS_SELECTOR, "div.landing-footer__main div.landing-footer__menu.landing-footer__step1:nth-child(1) div.landing-footer__block-body div.landing-footer__link-group.landing-footer__link-group--flexed.landing-footer__link-group--UA.landing-footer__link-group--lang-uk p:nth-child(1) > a:nth-child(1)")
    COMPANY_BUTTON = (By.CSS_SELECTOR, "div.landing-footer__menu.landing-footer__step1:nth-child(1) div.landing-footer__block-body div.landing-footer__link-group.landing-footer__link-group--flexed.landing-footer__link-group--UA.landing-footer__link-group--lang-uk p:nth-child(2) > a:nth-child(1)")
    TARIFF_BUTTON = (By.CSS_SELECTOR,"div.landing-footer__menu.landing-footer__step1:nth-child(1) div.landing-footer__block-body div.landing-footer__link-group.landing-footer__link-group--flexed.landing-footer__link-group--UA.landing-footer__link-group--lang-uk p:nth-child(5) > a:nth-child(1)")
    DISTANCE_BUTTON = (By.CSS_SELECTOR,"div.landing-footer__main div.landing-footer__menu.landing-footer__step1:nth-child(1) div.landing-footer__block-body div.landing-footer__link-group.landing-footer__link-group--flexed.landing-footer__link-group--UA.landing-footer__link-group--lang-uk p:nth-child(6) > a:nth-child(1)")
    COIN_BUTTON = (By.CSS_SELECTOR,"div[class='landing-footer__link-group landing-footer__link-group--flexed landing-footer__link-group--UA landing-footer__link-group--lang-uk'] [href='//nextua.transportica.com/uk/tr-coin/']")
    ABOUT_BUTTON = (By.CSS_SELECTOR,"div[class='landing-footer__link-group landing-footer__link-group--flexed landing-footer__link-group--UA landing-footer__link-group--lang-uk'] [href='//nextua.transportica.com/uk/about-us/']")
    PRICE_BUTTON = (By.CSS_SELECTOR,"div[class='landing-footer__link-group landing-footer__link-group--flexed landing-footer__link-group--UA landing-footer__link-group--lang-uk'] [href='//nextua.transportica.com/uk/prices/']")
    PRICE_BUTTON_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1]")
    PRICE_BUTTON_SHIPPERS = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[2]/a[1]/button[1]")
    QUESTION_BUTTON = (By.CSS_SELECTOR,"div[class='landing-footer__link-group landing-footer__link-group--flexed landing-footer__link-group--UA landing-footer__link-group--lang-uk'] [href='//nextua.transportica.com/uk/faq/']")
    SUBMIT_APPLICATION = (By.CSS_SELECTOR,"div.landing-footer__block-body div.landing-footer__link-group:nth-child(1) div.landing-footer__make-order.desktop.ng-scope > button.landing-light-green")
    #######################Q&A######################
    HOW_IT_WORK = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[1]/a[1]")
    CHANGE_PASS = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[2]/a[1]")
    APPLICATION = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[3]/a[1]")
    I_HAVE_A_DRIVER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[4]/a[1]")
    OWNER_OF_A_AUTOPARK = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[5]/a[1]")
    HOW_TO_SORT_ORDERS = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[6]/a[1]")
    DRIVER_IN_COMPANY = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[7]/a[1]")
    DRIVER_FORGOT_END_ORDER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[8]/a[1]")
    MONEY_FOR_DELIVERY = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[9]/a[1]")
    PAYMENT_MOMENT = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[10]/a[1]")
    WRONG_POINT = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[11]/a[1]")
    HOW_TO_REGISTER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[12]/a[1]")
    HOW_TO_DOWNLOAD_DOCUMENTS = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[13]/a[1]")
    HOW_TO_ADD_CAR = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[14]/a[1]")
    HOW_TO_TAKE_ORDER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[15]/a[1]")
    HOW_TO_DOWNLOAD_APP = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[16]/a[1]")
    HOW_TO_TAKE_MONEY = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[17]/a[1]")
    HOW_MAKING_PRICE = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[18]/a[1]")
    HOW_TO_CANSEL_ORDER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[19]/a[1]")
    HOW_TO_CALL_OPERATOR = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[20]/a[1]")
    HOW_IT_WORK_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[1]/a[1]")
    HOW_SERVICE_PAYMENT_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[2]/a[1]")
    CARGO_INFORMATION_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[3]/a[1]")
    CARGO_CHANGE_CONDITIONS_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[4]/a[1]")
    CARGO_WHERE_TRANSPORT_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[2]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[5]/a[1]")
    BUTTON_BACK_QA = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/span[3]/a[1]")
    BUTTON_BACK_MAIN = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/span[1]/a[1]")
    
    


class Header():
    HEADER_CARGO = (By.CSS_SELECTOR, "div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(2) a:nth-child(1) > span:nth-child(1)")
    HEADER_CARGO_SUBMIT_APPLICATION = (By.CSS_SELECTOR,"ul.main-page-header.ng-scope li.hovered:nth-child(2) div.choose-item.item-driver.no-img:nth-child(2) div.item > a:nth-child(1)")
    HEADER_TRANSPORT = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered.ng-scope:nth-child(3) a:nth-child(1) > span:nth-child(1)")
    HEADER_SEARCH_FOR_TRANSPORT = (By.CSS_SELECTOR,"li.hovered.ng-scope:nth-child(3) div.choose-item.item-driver.no-img:nth-child(2) div.item:nth-child(1) > a:nth-child(1)")
    HEADER_SEARCH_FOR_LOADING_VEHICLE = (By.CSS_SELECTOR,"li.hovered.ng-scope:nth-child(3) div.choose-item.item-driver.no-img:nth-child(2) div.item:nth-child(2) > a:nth-child(1)")
    HEADER_CALCULATOR = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(4) a:nth-child(1) > span:nth-child(1)")
    HEADER_TARIFF_CALCULATION = (By.CSS_SELECTOR,"div.choose-item.item-driver.no-img.calculate:nth-child(2) div.item:nth-child(1) > a:nth-child(1)")
    HEADER_PLACE_ROUTE = (By.CSS_SELECTOR,"div.choose-item.item-driver.no-img.calculate:nth-child(2) div.item:nth-child(2) > a:nth-child(1)")
    HEADER_COMPANY = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(5) a.drivers-link > span.colored")
    HEADER_FOR_PRIVATE_DRIVERS = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(5) div.choose-item.item-driver div.item:nth-child(1) > a:nth-child(2)")
    HEADER_FOR_TRANSPORT_COMPANY = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(5) div.choose-item.item-driver div.item:nth-child(2) > a:nth-child(2)")
    HEADER_ENTRY = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(6) a.signin > span:nth-child(1)")
    HEADER_ENTRY_FOR_COMPANY = (By.CSS_SELECTOR,"header.header .wrapper nav.top-menu ul.main-page-header>li .choose-item.item-sign .item a")
    HEADER_ENTRY_FOR_CUSTOMER = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.hovered:nth-child(6) div.choose-item.item-sign div.item:nth-child(2) > a:nth-child(2)")
    HEADER_ALERT_PHONE = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[1]/div[1]/input[1]")
    HEADER_ALERT_PASSWORD = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[2]/input[1]")
    HEADER_ALERT_BUTTON = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[3]/div[1]/button[1]")
    HEADER_LANGUAGE = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li.with-countries.ng-scope:nth-child(9) a:nth-child(1) p.choose-languages-links > span.choose-languages-links__language.ng-binding.ng-scope.active:nth-child(1)")
    HEADER_ALERT_EMAIL = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/input[1]")
    HEADER_ALERT_PASSWORD_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/input[1]")
    HEADER_ALERT_BUTTON_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[3]/div[1]/button[1]")
    HEADER_ALERT_DRIVER_NUMBER = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[1]/div[1]/input[1]")
    HEADER_ALERT_DRIVER_PASSWORD = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[2]/input[1]")
    HEADER_ALERT_SWITCHING_TO_CUSTOMER = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/p[1]")
    HEADER_ALERT_SWITCHING_TO_COMPANY = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]")
    HEADER_ALERT_COMPANY_NEW_PASS = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[2]/a[1]")
    HEADER_ALERT_CUSTOMER_NEW_PASS = (By.CSS_SELECTOR,"div.new-login-modal div.login-block form.ng-pristine.ng-valid div.wrapper:nth-child(2) > a.new-forgotPass:nth-child(3)")
    HEADER_ALERT_COMPANY_NEW_ACCAUNT = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[3]/div[1]/a[1]")
    HEADER_ALERT_CUSTOMER_NEW_ACCAUNT = (By.CSS_SELECTOR,"div.modal-content div.new-login-modal.ng-scope:nth-child(1) div.modal-login-wrapper:nth-child(2) div.new-login-modal div.login-block form.ng-pristine.ng-valid div.wrapper:nth-child(3) div.login-footer > a.login-footer__register")
    HEADER_ALERT_CUSTOMER_CREATE_ACCAUNT = (By.CSS_SELECTOR,"div.register-wrapper div.buttons-choose div.choose-wrapper.choose-client > button.client-button:nth-child(1)")
    HEADER_ALERT_COMPANY_CREATE_ACCAUNT = (By.CSS_SELECTOR,"div.buttons-choose div.driver-company-wrapper div.choose-wrapper.choose-company:nth-child(2) a:nth-child(1) > button.company-button")
    HEADER_ALERT_DRIVER_CREATE_ACCAUNT = (By.CSS_SELECTOR,"div.register-wrapper div.buttons-choose div.driver-company-wrapper div.choose-wrapper.choose-driver:nth-child(1) a:nth-child(1) > button.driver-button")
    HEADER_ALL_REGISTER_BUTTON = (By.CSS_SELECTOR,"div.wrapper nav.top-menu ul.main-page-header.ng-scope li:nth-child(8) > a.signup")
    HEADER_ALERT_CUSTOMER_PASS = (By.CSS_SELECTOR,".customModal.restore-password .modalContent h2")
    HEADER_ALERT_PRIVATE_ACCAUNT = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]")
    HEADER_ALERT_CUSTOMER_ACCAUNT = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/h2[1]")

    #######REGISTER_CUSTOMER#########
    HEADER_ALERT_CUSTOMER_REGISTER_NAME = (By.CSS_SELECTOR,"div.wrapper form.ng-pristine.ng-valid.ng-valid-mask div.input-wrapper:nth-child(3) > input.default.ym-record-keys.ng-pristine.ng-untouched.ng-valid.ng-empty.invalid-model:nth-child(2)")
    HEADER_ALERT_CUSTOMER_REGISTER_PHONE = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/input[1]")
    HEADER_ALERT_CUSTOMER_REGISTER_MAIL = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/input[1]")
    HEADER_ALERT_CUSTOMER_REGISTER_PASS = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[5]/input[1]")
    HEADER_ALERT_CUSTOMER_REGISTER_CONDITIONS = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[6]/div[1]")
    HEADER_ALERT_CUSTOMER_REGISTER_AGREE = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[7]/button[1]")
    HEADER_CUSTOMER_REGISTER = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/ul[1]/li[6]/ul[1]/li[2]/a[1]")
    HEADER_CUSTOMER_EMAIL_VARIFICATION = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/p[2]")
    HEADER_CUSTOMER_TEXT = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/p[1]")
    HEADER_CUSTOMER_PRIVACY_POLICY = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[6]/label[1]/a[2]")
    HEADER_CUSTOMER_TERMS_OF_USE = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[6]/label[1]/a[1]")

    ###########REGISTER_DRIVER#########
    HEADER_DRIVER_FIRST_NAME = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]")
    HEADER_DRIVER_LAST_NAME = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_PHONE = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_PAYMENT_CASH = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[6]/td[2]/div[1]/div[1]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_REGISTER_PAYMENT_CARD = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[6]/td[2]/div[1]/div[1]/p[2]/label[1]/span[1]")
    HEADER_ALERT_DRIVER_REGISTER_PAYMENT_NOCASH = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[6]/td[2]/div[1]/div[2]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_REGISTER_PAYMENT_NOCASHPDV = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[6]/td[2]/div[1]/div[2]/p[2]/label[1]/span[1]")
    HEADER_DRIVER_REGISTER_PASS = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_CONDITIONS = (By.CSS_SELECTOR,"div.register-page.ng-scope div.register-form.ng-scope:nth-child(3) div.register-footer:nth-child(3) div.rule > div.check:nth-child(1)")
    HEADER_DRIVER_REGISTER_AGREE = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.buttons button.default.blue.pull-right.landing-green > span:nth-child(1)")
    HEADER_ALERT_DRIVER_REGISTER_NOT_AGREE = (By.CSS_SELECTOR,"div.ng-scope:nth-child(6) div.register-wrapper.ng-scope div.register-page.ng-scope div.register-form.ng-scope:nth-child(3) div.register-footer:nth-child(3) div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_DRIVER_REGISTER_CONDITIONS_2 = (By.CSS_SELECTOR,"div.ng-scope:nth-child(6) div.register-wrapper.ng-scope div.register-page.ng-scope div.register-form.ng-scope:nth-child(3) div.register-footer:nth-child(3) div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_DRIVER_REGISTER_CONFIDENTIALITY = (By.CSS_SELECTOR,"div.rule label:nth-child(2) span.outbox span:nth-child(1) > a:nth-child(2)")
    HEADER_DRIVER_REGISTER_PHOTO = (By.CSS_SELECTOR,"input[type='file']")
    HEADER_DRIVER_REGISTER_MARK_CAR = (By.CSS_SELECTOR,"#mark")
    HEADER_DRIVER_REGISTER_YEAR_CAR = (By.CSS_SELECTOR,"#year")
    HEADER_DRIVER_REGISTER_NUMBER_CAR = (By.CSS_SELECTOR,"#license-plate")
    HEADER_DRIVER_REGISTER_CATEGORY_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/div[1]/div[1]/p[2]")
    HEADER_DRIVER_REGISTER_CATEGORY_CAR_TRUCK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/div[1]/div[2]/ul[1]/li[1]")
    HEADER_DRIVER_REGISTER_TYPE_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[1]/p[1]")
    HEADER_DRIVER_REGISTER_TYPE_CAR_TENT = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[1]")
    HEADER_DRIVER_REGISTER_TYPE_DOWNLOAD_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[1]/span[1]")
    HEADER_DRIVER_REGISTER_TYPE_DOWNLOAD_CAR_UPPER = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[1]/p[1]/label[1]")
    HEADER_DRIVER_REGISTER_PERMISSION_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[1]/span[2]")
    HEADER_DRIVER_REGISTER_PERMISSION_CAR_CMR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[1]/p[1]/label[1]")
    HEADER_DRIVER_REGISTER_DIMENSIONS_LENGTH_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[2]/tr[1]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_DIMENSIONS_HEIGHT_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[2]/tr[1]/td[2]/input[2]")
    HEADER_DRIVER_REGISTER_DIMENSIONS_WIDTH_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[2]/tr[1]/td[2]/input[3]")
    HEADER_DRIVER_REGISTER_VOLUME_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[2]/tr[3]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_CAPACITY_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[2]/tr[5]/td[2]/input[1]")
    HEADER_DRIVER_REGISTER_AGREE_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[1]")
    HEADER_DRIVER_REGISTER_BACK_CAR = (By.CSS_SELECTOR, "div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_DRIVER_REGISTER_BACK_CAR = (By.CSS_SELECTOR, "div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_ALERT_DRIVER_REGISTER_INPUT = (By.CSS_SELECTOR, "#sms")
    HEADER_ALERT_COMPANY_REGISTER_BUTTON = (By.CSS_SELECTOR, "div.buttons-choose div.driver-company-wrapper div.choose-wrapper.choose-company:nth-child(2) a:nth-child(1) > button.company-button")
    HEADER_DRIVER_ALERT_TEXT = (By.CSS_SELECTOR, ".customModal.errorModal .wrapper h3")
    HEADER_DRIVER_TEMP_OF_USE = (By.CSS_SELECTOR, "div.register-footer:nth-child(3) div.rule label:nth-child(2) span.outbox span:nth-child(1) > a:nth-child(1)")
    HEADER_DRIVER_PRIVACY_POLICY = (By.CSS_SELECTOR, "div.register-footer:nth-child(3) div.rule label:nth-child(2) span.outbox span:nth-child(1) > a:nth-child(2)")
    HEADER_DRIVER_NOT_AGREE = (By.CSS_SELECTOR, "div.register-footer:nth-child(3) div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_DRIVER_CAR_TEXT = (By.CSS_SELECTOR, "div.register-footer:nth-child(3) div.flex-container > p.error.ng-binding.ng-scope")
    HEADER_DRIVER_CAR_BACK = (By.CSS_SELECTOR, "div.register-footer:nth-child(3) div.buttons div.cancle-link.pull-left > a:nth-child(1)")
    HEADER_DRIVER_CAR_TRACK_TRAILER = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/div[1]/div[2]/ul[1]/li[2]")
    HEADER_DRIVER_CAR_MINIBUS = (By.XPATH, " /html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/div[1]/div[2]/ul[1]/li[3]")
    HEADER_DRIVER_CAR_VAN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/div[1]/div[2]/ul[1]/li[4]")
    HEADER_DRIVER_CAR_EVACUATOR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[2]")
    HEADER_DRIVER_CAR_CURTAIN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[3]")
    HEADER_DRIVER_CAR_CONTAINER20 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[11]")
    HEADER_DRIVER_CAR_TRACK_OUTSIZED = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[26]")
    HEADER_DRIVER_CAR_TRACK_BULK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[9]")
    HEADER_DRIVER_CAR_GAS_TANK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[8]")
    HEADER_DRIVER_CAR_TRAWL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[7]")
    HEADER_DRIVER_CAR_MANIPULATOR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[15]")
    HEADER_DRIVER_CAR_TIMBER = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/div[2]/ul[1]/li[3]")
    HEADER_DRIVER_CAR_LATERAL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[2]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_BACK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[3]/p[1]/label[1]")
    HEADER_DRIVER_CAR_FULL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[4]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_WITHOUT = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[5]/p[1]/label[1]")
    HEADER_DRIVER_CAR_WITHDRAWAL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[6]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_WITHDRAWAL_TRANSVERSE = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[7]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_GIDROBORD = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[8]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_TIR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[2]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_TI1 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[3]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_TI2 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[4]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR1 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[5]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR2 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[6]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR3 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[7]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR4 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[8]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR5 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[9]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR6 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[10]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR7 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[11]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR8 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[12]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_ADR9 = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[13]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_EKMT = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[14]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_SAN = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[15]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_SANBOOK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[16]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_CUSTOMS = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[17]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_CUSTOM_CONTROL = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[18]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_CAR_NUMBER_OF_TRUCK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[1]/td[2]/input[1]")
    HEADER_DRIVER_CAR_LOAD_DIMENSIONS_L = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[2]/td[2]/input[1]")
    HEADER_DRIVER_CAR_LOAD_DIMENSIONS_W = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[2]/td[2]/input[2]")
    HEADER_DRIVER_CAR_LOAD_DIMENSIONS_H = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[2]/td[2]/input[3]")
    HEADER_DRIVER_CAR_MAX_VOLUME = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[4]/td[2]/input[1]")
    HEADER_DRIVER_CAR_CARGO_CAPACITY = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[3]/tr[6]/td[2]/input[1]")
    HEADER_DRIVER_MICRO_TYPE = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[6]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_MICRO_TYPE_LIST = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/checklist-dropdown[1]/div[1]/div[1]/span[1]")
    HEADER_DRIVER_MICRO_AGREE_LIST = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[1]")
    HEADER_DRIVER_MICRO_AGREE_SMR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[1]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_NOCATEGORY_LIST = (By.CSS_SELECTOR, "p[class='placeholder ng-scope']")
    HEADER_DRIVER_NOCATEGORY_BUTTON = (By.CSS_SELECTOR, "#transporter")
    HEADER_DRIVER_REGISTER_PERMISSION_CAR_OUTBOX = (By.CSS_SELECTOR, ".outbox ng-binding")
    HEADER_DRIVER_VAN_LIST = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/checklist-dropdown[1]/div[1]/div[1]/span[1]")
    HEADER_DRIVER_VAN_BACK = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[3]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_VAN_H = (By.CSS_SELECTOR, "#transport-width")
    HEADER_DRIVER_VAN_W = (By.CSS_SELECTOR, "#transport-height")
    HEADER_DRIVER_VAN_DOWNLOAD = (By.CSS_SELECTOR, "div.register-form.ng-scope tr.ng-scope:nth-child(5) td:nth-child(2) checklist-dropdown.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope.ng-not-empty div.checklist-dropdown > div.dropdown-field")
    HEADER_DRIVER_VAN_DOWNLOAD_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[4]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_VAN_PERMISION_CAR = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[1]")
    HEADER_DRIVER_VAN_PERMISION_CAR_VARIANT = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/checklist-dropdown[1]/div[1]/div[2]/div[2]/div[6]/p[1]/label[1]/span[1]")
    HEADER_DRIVER_AGREE_TEXT = (By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/p[1]")
    HEADER_DRIVER_AGREE_ALERT = (By.CSS_SELECTOR, ".customModal.errorModal")
    HEADER_DRIVER_TEXT = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.flex-container > p.error.ng-binding.ng-scope")
    
    

    #############REGISTER_COMPANY##############
    HEADER_COMPANY_REGISTER_PHONE = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_MANAGEMENT = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/div[1]/div[1]/p[1]")
    HEADER_COMPANY_REGISTER_MANAGEMENT_FLP = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/div[1]/div[2]/ul[1]/li[2]")
    HEADER_COMPANY_REGISTER_LEGAL_ENTITY = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_CONTACT_PERSON = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_UID2 = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[6]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_MAIL = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[7]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_PASS = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[8]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_CONDITIONS = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.rule > div.check:nth-child(1) ")
    HEADER_COMPANY_REGISTER_AGREE = (By.CSS_SELECTOR,"div.buttons button.default.blue.pull-right.landing-green > span:nth-child(1)")
    HEADER_COMPANY_REGISTER_NOT_AGREE = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.buttons div.cancle-link > a:nth-child(1)")
    HEADER_COMPANY_ALERT_DRIVER = (By.CSS_SELECTOR,"div.modal-footer > button.modalSave.blue.ng-binding")####
    HEADER_COMPANY_REGISTER_DRIVER_FIRST_NAME = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_DRIVER_LAST_NAME = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_DRIVER_PHONE = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_DRIVERS_LICENSE = (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]")
    HEADER_COMPANY_REGISTER_AGREE = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.buttons > button.default.blue.pull-right.landing-green")
    HEADER_COMPANY_MAIN_BUTTON = (By.CSS_SELECTOR,"div.map-links span.link:nth-child(1) > a:nth-child(1)")
    HEADER_COMPANY_TEXT = (By.CSS_SELECTOR,".register-wrapper .register-page .register-footer .flex-container p.error")
    HEADER_COMPANY_TEMP_OF_USE = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.rule label:nth-child(2) span.outbox > a:nth-child(1)")
    HEADER_COMPANY_PRIVACY_POLICY = (By.CSS_SELECTOR,"div.register-footer:nth-child(3) div.rule label:nth-child(2) span.outbox > a:nth-child(2)")
    HEADER_COMPANY_NEW_PASS = (By.CSS_SELECTOR,"div.customModal.restore-password.ng-scope div.modalContent > h2.ng-binding:nth-child(2)")
    COMPANY_VERIFICATION_BUTON = (By.CSS_SELECTOR,".smsCode .modalSave")
    #######MODERETION########
    MODERETION_LOGIN = (By.XPATH,"/html[1]/body[1]/div[1]/form[1]/div[2]/input[1]")
    MODERETION_PASS = (By.XPATH,"/html[1]/body[1]/div[1]/form[1]/div[2]/input[2]")
    MODERETION_BUTTON = (By.XPATH,"/html[1]/body[1]/div[1]/form[1]/div[2]/button[1]")
    MODERETION_COMPANY = (By.CSS_SELECTOR,"div.application.ng-scope:nth-child(1) div.company.ng-scope header.company-header.ng-scope ul:nth-child(4) li.active:nth-child(2) > a:nth-child(1)")
    MODERETION_BUTTON = (By.XPATH,"/html[1]/body[1]/div[1]/form[1]/div[2]/button[1]")
    MODERETION_VERIFICATION = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/header[1]/div[2]/a[5]")
    MODERETION_VERIFICATION_PHONE = (By.CSS_SELECTOR,"div.registration-codes-wrapper:nth-child(2) table:nth-child(3) tbody:nth-child(1) tr.ng-scope td:nth-child(1) > a.ng-scope")
    MODERETION_VERIFICATION_CODE = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/span[1]")
    MODERETION_COMPANY_VERIFICATION = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/input[1]")
    MODERETION_COMPANY_VERIFICATION_BUTTON = (By.CSS_SELECTOR,"div.modal-dialog div.modal-content div.customModal.smsCode.ng-scope div.modalFooter div.modal-footer > button.modalSave:nth-child(1)")
    MODERETION_COMPANY_VERIFICATION_BUTTON_AGAIN = (By.CSS_SELECTOR,"div.modal-content div.customModal.smsCode.ng-scope div.modalFooter div.modal-footer > a:nth-child(2)")
    MODERETION_CUSTUMER = (By.XPATH,"div.container-aside.ng-scope aside.fixed-menu ul.list-items-wrapper.ng-scope > li.ng-scope:nth-child(1)")
    MODERETION_CUSTUMER_BUTTON = (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/aside[1]/ul[1]/li[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/span[1]")
    MODERETION_CUSTUMER_VERIFICATION = (By.CSS_SELECTOR,"div.container-aside.ng-scope aside.fixed-menu ul.list-items-wrapper.ng-scope > li.ng-scope:nth-child(1)")
    



